version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:2022.01
    steps:
      - run:
          name: job1.step1.run
          command: |
            echo pipeline.git.revision << pipeline.git.revision >>
            echo pipeline.git.tag << pipeline.git.tag >>
            echo pipeline.git.branch << pipeline.git.branch >>

workflows:
  w1:
    jobs:
      - job1
